import crypto from 'crypto';

// Both the website and the admin panel must share the SAME UNSUBSCRIBE_SECRET so
// that a token generated by one app verifies on whichever app hosts the route.
const SECRET =
  process.env.UNSUBSCRIBE_SECRET ||
  process.env.RESEND_API_KEY || // fallback so links work pre-config; set UNSUBSCRIBE_SECRET in prod
  'hhm-unsub-dev-secret';

// Public origin that hosts /api/unsubscribe (the public website). Both apps point here.
export const UNSUB_BASE =
  process.env.PUBLIC_SITE_URL ||
  process.env.NEXT_PUBLIC_APP_URL ||
  'https://heavenshospitality.org';

const b64url = (i: Buffer | string) => Buffer.from(i).toString('base64url');

// Opaque, forgery-proof token = base64url(email).base64url(HMAC). No DB column needed.
export function makeUnsubToken(email: string): string {
  const e = email.trim().toLowerCase();
  const sig = crypto.createHmac('sha256', SECRET).update(e).digest();
  return `${b64url(e)}.${b64url(sig)}`;
}

export function verifyUnsubToken(token: string): string | null {
  if (!token || !token.includes('.')) return null;
  const [ePart, sPart] = token.split('.');
  let email: string;
  let got: Buffer;
  try {
    email = Buffer.from(ePart, 'base64url').toString('utf8');
    got = Buffer.from(sPart, 'base64url');
  } catch {
    return null;
  }
  const expected = crypto.createHmac('sha256', SECRET).update(email).digest();
  if (got.length !== expected.length) return null;
  return crypto.timingSafeEqual(got, expected) ? email : null;
}

export function unsubscribeUrl(email: string): string {
  return `${UNSUB_BASE}/api/unsubscribe?token=${encodeURIComponent(makeUnsubToken(email))}`;
}
